apiVersion: v1
kind: ReplicationController 
metadata: 
  name: mynginx-rc 
spec: 
  replicas: 2
  selector: 
    app: myjavacontainer
    version: 2.6.1
  template: 
    metadata: 
      labels: 
        app: myjavacontainer
        version: 2.6.1
    spec: 
      containers: 
      - name: mynginx-container
        image: raiyan19/myjavaapp111223:1 
        ports:
          - containerPort: 8080
  